### ISSUE TITLE
Need new feature to edit or update rules from ruby code?

### ISSUE THREAD

**Issue by vijayaragavang** [r-cochran/cuke_sniffer#61]
Hi, 
     Planning to customise rules for cucumber from ruby code because few rules cant be followed as you defined . Is there any provision available to update rules?
  For example , in our feature file has to many scenarios (more than 10) and plan to set limit as 20.

**Comment by enkessler** [comment]
@r-cochran This is still 'clunky'. Is there any update on when this might become more user friendly?
